apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.30"
vpc:
  id: vpc-007da96d934e37ef2
  securityGroup: "sg-0e79befce4564b56b"
  subnets:
    private:
      us-east-1a: { id: subnet-009fcea91a4a8b74f }
      us-east-1b: { id: subnet-09ee5943e3891efc6 }
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  serviceRoleARN: "arn:aws:iam::383255430480:role/EksClusterRole"
  withOIDC: true
managedNodeGroups:
  - name: eks-nodes
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    instanceType: t3.medium
    iam:
      instanceRoleARN: arn:aws:iam::383255430480:role/EksNodeRole
